### ISSUE TITLE
[Setting] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by cchanmi** [31st-IN-SOPT-iOS-Part/ChanmiHwang#1]
## 🍎 이슈 요약

- 프로젝트 초기 세팅

## ✅ 체크 리스트
- [ ] 라이브러리 설치
- [ ] 스토리보드 연결 해제
- [ ] 폴더링

**Comment by pcsoyeon** [comment]
언냐 빨리 해줘요. 오늘까지 과제 제출 아녀요? 아님 말고 .. 황짠미 찬마 별빛찬미 화이팅~!~!~!

**Comment by uxri** [comment]
> 언냐 빨리 해줘요. 오늘까지 과제 제출 아녀요? 아님 말고 .. 황짠미 찬마 별빛찬미 화이팅~!~!~!

언냐 나도 기다리고 있음요. 별빛찬미벌먹찬미찬마찬마화이팅><~~~~~!

**Comment by cchanmi** [comment]
@pcsoyeon @uxri 사랑해 내 여자들 쪽.
